window.periodResources={
prehistoric:{books:[['Oral creation traditions','Multiple communities · before writing','Stories carried cosmology, ancestry, law, and ecological knowledge through performance. Visual symbols and ritual objects worked beside this living literature.'],['The Pyramid Texts','Egypt · c. 2400–2300 BCE','These early sacred inscriptions show older oral and ritual ideas becoming a durable system of language and image.'],['The Epic of Gilgamesh','Mesopotamian oral roots · later written versions','Older stories of kingship, mortality, friendship, and flood memory preserve concerns formed as cities emerged.']],core:['FRA','ESP','DEU','ZAF','IDN','AUS','ARG','CHL'],influence:['GBR','IRL','PRT','ITA','TUR','ISR','IND','CHN','JPN','MEX','PER','BRA'],note:'“Prehistoric” is not one style or one place. Highlights mark representative archaeological sites; image-making developed independently across inhabited regions.'},
ancient:{books:[['The Epic of Gilgamesh','Mesopotamia · compiled c. 2100–1200 BCE','The epic joined kingship, divine power, mortality, and city identity—the same forces monumental art made visible.'],['The Iliad and The Odyssey','Homeric tradition · c. 8th century BCE','These epics shaped Greek ideals of heroism, fate, hospitality, and memory, supplying subjects for pottery, sculpture, and theater.'],['The Republic','Plato · c. 375 BCE','Justice, education, imitation, and the philosopher’s ascent toward truth connect political order to Plato’s larger theory of intelligible Forms: ideals more stable than their physical examples.']],core:['EGY','IRQ','IRN','GRC','ITA','TUR','IND','CHN','MEX','PER'],influence:['ESP','FRA','GBR','DEU','ISR','JOR','LBN','SYR','PAK','AFG','JPN','KOR'],note:'“Ancient” contains many independent civilizations. Core regions identify major traditions; lighter regions show exchange, conquest, and enduring reception.'},
medieval:{books:[['The Qur’an','Arabia · 7th century','Revelation, recitation, and the written word transformed architecture, calligraphy, ornament, learning, and exchange across the Islamic world.'],['The Tale of Genji','Murasaki Shikibu · early 11th century','Court life, emotion, seasons, and aesthetics shaped Japanese literature and a long tradition of illustrated narrative.'],['The Divine Comedy','Dante Alighieri · c. 1308–1321','Dante organized theology, politics, classical learning, and experience into a journey that inspired centuries of Christian imagery.']],core:['GBR','IRL','FRA','ESP','PRT','ITA','DEU','CZE','POL','GRC','TUR'],influence:['NOR','SWE','DNK','AUT','HUN','HRV','SRB','ROU','BGR','UKR','ISR','LBN','SYR','EGY','TUN','DZA','MAR'],note:'This map locates the European and Mediterranean tradition described here. Other societies had distinct, equally complex contemporaneous histories.'},
renaissance:{books:[['The Prince','Niccolò Machiavelli · 1532','Its unsentimental analysis of power reflected competitive courts and the humanist habit of studying human action on its own terms.'],['In Praise of Folly','Desiderius Erasmus · 1511','Humanist satire used classical learning to criticize religious and social institutions amid the disruptive spread of print and reform.'],['Hamlet','William Shakespeare · c. 1600','Its inward protagonist reflects Renaissance interest in individual consciousness, performance, politics, and unstable appearances.']],core:['ITA','NLD','BEL','DEU','FRA','GBR','ESP'],influence:['PRT','CHE','AUT','CZE','POL','HUN','HRV','GRC'],note:'The Renaissance label centers Europe. Trade, diplomacy, empire, and print extended its forms, often through unequal colonial encounters.'},
baroque:{books:[['Don Quixote','Miguel de Cervantes · 1605/1615','Shifting realities, theatrical self-awareness, and the collision of ideal and experience parallel Baroque fascination with illusion.'],['Discourse on Method','René Descartes · 1637','Systematic doubt expressed a century negotiating between inherited religious authority and new scientific ways of knowing.'],['Paradise Lost','John Milton · 1667','Epic scale, spiritual conflict, political rebellion, and sensory language made a literary counterpart to Baroque drama.']],core:['ITA','ESP','FRA','BEL','NLD','AUT','DEU'],influence:['PRT','GBR','CZE','POL','HRV','MEX','PER','BRA','PHL'],note:'Baroque forms moved through missions, courts, trade, and empire. Local makers transformed imported models rather than simply copying Europe.'},
neoclassicism:{books:[['Encyclopédie','Diderot and d’Alembert · 1751–1772','Organized, illustrated knowledge embodied Enlightenment confidence in reason, education, technical skill, and reform.'],['The Social Contract','Jean-Jacques Rousseau · 1762','Popular sovereignty and civic obligation gave revolutionary urgency to art about sacrifice, citizenship, and the republic.'],['A Vindication of the Rights of Woman','Mary Wollstonecraft · 1792','Its demand for women’s education exposed exclusions inside supposedly universal Enlightenment ideals.']],core:['FRA','GBR','ITA','USA','DEU'],influence:['ESP','PRT','NLD','BEL','CHE','AUT','POL','GRC','MEX','BRA','ARG'],note:'Classical revival served republics, monarchies, and empires. Archaeology, print, revolution, and colonial institutions carried it widely.'},
romanticism:{books:[['Lyrical Ballads','Wordsworth and Coleridge · 1798','Ordinary language, imagination, memory, and nature helped define the Romantic rejection of inherited rules.'],['Faust','Johann Wolfgang von Goethe · 1808/1832','Restless ambition, knowledge, desire, folklore, and spiritual consequence formed a defining image of the modern individual.'],['Frankenstein','Mary Shelley · 1818','Creator and creature made scientific ambition, isolation, responsibility, and industrial modernity emotionally immediate.']],core:['GBR','DEU','FRA','ESP'],influence:['ITA','CHE','AUT','POL','CZE','NOR','SWE','DNK','RUS','USA','MEX'],note:'Romanticism developed through connected literary, musical, and visual movements. National traditions differed while revolution and empire carried its themes.'},
realism:{books:[['The Communist Manifesto','Karl Marx and Friedrich Engels · 1848','Its account of class conflict gave language to industrial conditions and social tensions Realist artists placed in view.'],['Madame Bovary','Gustave Flaubert · 1857','Detailed observation and critique of provincial desire challenged romantic illusion, paralleling painting’s contemporary turn.'],['Middlemarch','George Eliot · 1871–1872','Interwoven lives reveal how economics, gender, reform, and private choices shape a community.']],core:['FRA','GBR','RUS'],influence:['BEL','NLD','DEU','ESP','ITA','NOR','SWE','USA','MEX'],note:'Realist practices emerged differently across industrializing societies. Journalism, upheaval, exhibitions, and translation spread its commitment to contemporary life.'},
impressionism:{books:[['The Flowers of Evil','Charles Baudelaire · 1857','Urban crowds, fleeting beauty, sensation, and alienation helped define the modern life Impressionists painted.'],['Nana','Émile Zola · 1880','The novel maps entertainment, money, class, and spectacle across the social world of modern Paris.'],['The Work','Émile Zola · 1886','A fictional avant-garde painter’s struggle captures the new exhibition system, criticism, rivalry, and cost of innovation.']],core:['FRA'],influence:['GBR','BEL','NLD','DEU','ITA','USA','JPN'],note:'Impressionism formed in France, but travel, collecting, exhibitions, photography, and Japanese prints made its visual exchange transnational.'},
'post-impressionism':{books:[['Thus Spoke Zarathustra','Friedrich Nietzsche · 1883–1885','Its challenge to inherited morality echoed artists seeking individual, symbolic, and transformative languages beyond naturalism.'],['The Yellow Wallpaper','Charlotte Perkins Gilman · 1892','Subjective perception and psychological confinement show social structures through an intensely personal visual world.'],['The Interpretation of Dreams','Sigmund Freud · 1899','The theory that images conceal psychic meaning prepared audiences for symbolism, expressionism, and Surrealism.']],core:['FRA','BEL','NLD'],influence:['GBR','DEU','AUT','CHE','ITA','ESP','NOR','RUS'],note:'Post-Impressionism was never a single group. Parisian dealer and exhibition networks connected distinct experiments later developed across Europe and beyond.'},
modernism:{books:[['Ulysses','James Joyce · 1922','Fragmented viewpoints, interior monologue, myth, and ordinary city life remade literary form as artists dismantled fixed perspective.'],['The Waste Land','T. S. Eliot · 1922','Quotation, fragments, multiple voices, and postwar dislocation made fragmentation a structure for modern experience.'],['The Second Sex','Simone de Beauvoir · 1949','Its analysis of socially produced gender transformed debate and helped artists challenge representation and institutional exclusion.']],core:['FRA','DEU','AUT','RUS','ITA','NLD','ESP','GBR','USA','MEX'],influence:['BEL','CHE','CZE','POL','HUN','BRA','ARG','JPN','IND'],note:'Modernism formed through migration and competing centers, then spread through schools, museums, exile, colonial networks, and mass reproduction.'},
contemporary:{books:[['Ways of Seeing','John Berger · 1972','Berger connected images to gender, class, reproduction, and ownership, offering tools for questioning visual power.'],['Orientalism','Edward Said · 1978','Its critique of Western representations reshaped art history, museum practice, and debates about empire and authority.'],['Beloved','Toni Morrison · 1987','Its treatment of slavery, memory, trauma, and the supernatural shows how form can recover histories official archives suppress.']],core:['USA','CAN','MEX','BRA','ARG','GBR','FRA','DEU','ITA','ZAF','NGA','EGY','IND','CHN','JPN','KOR','AUS'],influence:'all',note:'Contemporary art is globally networked but not evenly resourced. Highlights mark representative centers amid local histories and transnational exchange.'}
};

window.periodIdeas={
prehistoric:['Symbolic thought','A mark can stand for something absent. Images, stories, and ritual objects allowed communities to think beyond the immediate moment—toward memory, ancestry, possibility, and unseen forces.'],
ancient:['Ideal form','Plato distinguished changing physical examples from intelligible Forms. Every drawn circle is imperfect, but reason can grasp the definition of a perfect circle—an ideal against which examples are judged.'],
medieval:['An ordered cosmos','Much medieval thought understood reality as a meaningful hierarchy joining matter, humanity, and the divine. Knowledge sought relationships within that order, not isolated facts alone.'],
renaissance:['Humanism','Classical learning and close observation made human agency, dignity, language, and historical judgment central concerns without simply abandoning religious belief.'],
baroque:['Doubt and appearance','Scientific discovery and religious conflict made perception unstable. Thinkers asked what could be known with certainty while artists demonstrated how vision could be directed.'],
neoclassicism:['Reason and universal rights','Enlightenment thinkers argued that society could be redesigned through reason. Their universal claims inspired reform and revolution while exposing exclusions from citizenship.'],
romanticism:['Imagination as knowledge','Feeling, intuition, memory, and the sublime became ways of knowing that challenged pure rationalism and the mechanical logic of industrial society.'],
realism:['Material and social conditions','Thought turned toward observable institutions, labor, class, and environment. Individual lives were understood as shaped by systems rather than heroic will alone.'],
impressionism:['Perception is an event','Seeing is not neutral recording. Light, time, movement, attention, and the observer’s position continually reconstruct what the world looks like.'],
'post-impressionism':['Inner reality','A visible scene could be reorganized by emotion, symbolism, geometry, or optical theory. Truth no longer required a single naturalistic appearance.'],
modernism:['Fragmented modern experience','Psychology, relativity, war, machines, and mass media weakened confidence in one stable viewpoint. Form itself became a method for investigating reality.'],
contemporary:['Situated knowledge','Meaning depends on identity, history, power, medium, and participation. Contemporary thought asks who speaks, whose knowledge counts, and how systems shape what can be seen.']
};
