const periods = [
  {id:'prehistoric',name:'Prehistoric Art',date:'c. 40,000–3,000 BCE',summary:'The first surviving images reveal communities using marks, objects, and places to think beyond the immediate present.',art:'Firelight, mineral pigment, animal movement, and the human hand turn a cave wall into shared memory.',impacts:['Political|Small kin-based communities used ritual places and precious objects to reinforce belonging, leadership, and shared identity.','Social|Images carried knowledge between generations when memory, story, and ceremony were the primary archives.','Economic|Hunting, gathering, then settled agriculture changed materials and subjects; surplus time supported specialized making.','Military|Hunting technologies and territorial competition shaped animal imagery, weapons, fortified settlements, and status objects.'],works:['Lascaux Cave Paintings|Unknown makers · c. 17,000 BCE|Layered animal images use the cave’s contours to create movement.','Venus of Willendorf|Unknown maker · c. 25,000 BCE|A portable figure concentrates attention on the body, fertility, and survival.','Stonehenge|Unknown communities · c. 3000–2000 BCE|Landscape, labor, astronomy, and ceremony converge in monumental stone.'],design:['Shelter|Timber, hide, woven reed, and earth made architecture local, adaptable, and communal.','Objects|Carved bone, stone vessels, baskets, and pottery joined utility with repeated symbolic pattern.','Legacy|Material honesty, biomorphic form, and collective building remain recurring design ideals.']},
  {id:'ancient',name:'Ancient Art',date:'c. 3,000 BCE–400 CE',summary:'Art made gods, rulers, laws, and civic ideals visible across the first great urban civilizations.',art:'Monumental scale, ideal bodies, durable stone, and measured geometry promise order against time.',impacts:['Political|Kings, pharaohs, emperors, and city-states used monuments and portraits to legitimize rule.','Social|Public temples, theaters, baths, and tombs organized communities by citizenship, class, gender, and belief.','Economic|Agricultural surplus, taxation, slavery, and long-distance trade funded specialized workshops and vast building programs.','Military|Conquest spread styles, materials, artists, and propaganda; victory monuments converted warfare into public memory.'],works:['Bust of Nefertiti|Thutmose workshop · c. 1345 BCE|Idealization and intimate observation combine in a royal image.','The Parthenon|Iktinos and Kallikrates · 447–432 BCE|Architecture turns proportion and civic religion into a unified statement.','Augustus of Prima Porta|Unknown Roman sculptor · early 1st c. CE|An emperor’s body becomes a carefully controlled political message.'],design:['Architecture|Columns, post-and-lintel systems, arches, vaults, and domes created enduring civic types.','Furniture|Egyptian stools, Greek klismos chairs, bronze lamps, and Roman couches balanced status and utility.','Ornament|Lotus, meander, acanthus, mosaic, and narrative relief became a shared decorative vocabulary.']},
  {id:'medieval',name:'Medieval Art',date:'c. 400–1400',summary:'Sacred images and soaring buildings made an invisible spiritual order tangible in a fragmented world.',art:'Gold, symbol, pattern, colored glass, and vertical space redirect attention from earthly appearance to sacred meaning.',impacts:['Political|After Rome, courts, monasteries, feudal lords, and the Church became overlapping centers of authority and patronage.','Social|Pilgrimage, worship, and manuscript culture connected dispersed communities through shared images and stories.','Economic|Monastic estates, guilds, trade towns, and cathedral fundraising sustained generations of skilled makers.','Military|Invasions, Crusades, fortified castles, and contact with Islamic cultures moved objects, techniques, and motifs across regions.'],works:['Book of Kells|Insular monastic artists · c. 800|Script, animal interlace, and sacred symbol become a dense field of devotion.','Bayeux Tapestry|Unknown embroiderers · c. 1070s|A continuous narrative records conquest through image and inscription.','Chartres Cathedral|Many workshops · begun 1194|Stone structure and stained light create a total sacred environment.'],design:['Architecture|Pointed arches, rib vaults, and flying buttresses opened walls to colored glass and height.','Furniture|Portable chests, trestle tables, carved choir stalls, and heavy oak reflected mobile courts and guild craft.','Design|Illumination, tapestry, enamel, and metalwork joined teaching, ceremony, and surface pattern.']},
  {id:'renaissance',name:'The Renaissance',date:'c. 1400–1600',summary:'Humanism, observation, and classical learning recast the artist as an intellectual and the world as measurable space.',art:'Perspective, anatomical attention, balanced composition, and atmospheric light make the visible world newly convincing.',impacts:['Political|Competitive city-states, courts, popes, and merchant dynasties used culture to project legitimacy and sophistication.','Social|Humanist education elevated individual achievement while print widened access to images and classical ideas.','Economic|Banking, Mediterranean trade, and workshop systems concentrated wealth in cities and created an art market.','Military|Gunpowder warfare reshaped fortifications; invasions and diplomatic rivalry circulated artists and styles across Europe.'],works:['The Birth of Venus|Sandro Botticelli · c. 1485|Classical myth becomes a vehicle for beauty, poetry, and elite humanism.','Mona Lisa|Leonardo da Vinci · c. 1503–19|Subtle light and psychological presence transform portraiture.','David|Michelangelo · 1501–04|An idealized civic hero joins anatomical study with political symbolism.'],design:['Architecture|Symmetry, domes, round arches, and classical orders made buildings appear rational and harmonious.','Furniture|Cassoni, walnut cabinets, sgabello chairs, intarsia, and velvet displayed learning and domestic status.','Graphic design|Print, roman type, diagrams, and measured drawing standardized visual knowledge.']},
  {id:'baroque',name:'Baroque',date:'c. 1600–1750',summary:'In an age of religious conflict and expanding states, art became a persuasive theater of movement, light, and power.',art:'Diagonal action, tenebrist light, sensory materials, and unstable space pull the viewer inside the event.',impacts:['Political|Absolute monarchs and powerful courts turned palaces, portraits, and ceremony into instruments of centralized authority.','Social|The Counter-Reformation sought emotionally direct art, while urban spectacle made public life theatrical.','Economic|Colonial wealth and global trade supplied pigments, luxury materials, and new markets—often through exploitation.','Military|Religious wars and imperial rivalry shaped maps, triumphal imagery, court display, and images of martyrdom and victory.'],works:['The Calling of St Matthew|Caravaggio · 1599–1600|A beam of light transforms an ordinary room into revelation.','David|Gian Lorenzo Bernini · 1623–24|Sculpture captures a body at the tense instant of action.','Judith Slaying Holofernes|Artemisia Gentileschi · c. 1612–13|Physical force and dramatic light give a familiar story visceral urgency.'],design:['Architecture|Oval plans, curved facades, illusionistic ceilings, and axial gardens choreographed movement and awe.','Furniture|Gilded consoles, marquetry cabinets, upholstered armchairs, and silver made interiors perform wealth.','Ornament|Scrolls, shells, acanthus, mirrors, and integrated ceiling painting dissolved boundaries between the arts.']},
  {id:'neoclassicism',name:'Neoclassicism',date:'c. 1750–1850',summary:'Archaeology and Enlightenment ideals revived antiquity as a language of reason, virtue, and revolution.',art:'Clear contour, shallow space, restrained color, and classical dress make moral choices feel public and permanent.',impacts:['Political|Revolutionaries and empires alike claimed Greece and Rome to frame new republics, citizenship, and imperial authority.','Social|Enlightenment debate promoted public museums and academies, though access and citizenship remained unequal.','Economic|Industrial wealth and an expanding middle class created markets for prints, ceramics, furnishings, and public architecture.','Military|Revolutionary and Napoleonic campaigns spread the style while looted antiquities filled new national museums.'],works:['Oath of the Horatii|Jacques-Louis David · 1784|Civic sacrifice is staged with severe geometry and sculptural clarity.','Cornelia, Mother of the Gracchi|Angelica Kauffman · c. 1785|Domestic virtue becomes a classical moral lesson.','George Washington|Horatio Greenough · 1840|A modern political leader is cast in the visual authority of antiquity.'],design:['Architecture|Temple fronts, domes, symmetrical plans, and pale stone gave banks and governments civic gravity.','Furniture|Tapered legs, klismos silhouettes, gilt mounts, and mahogany replaced Baroque curves with linear discipline.','Design|Urns, laurel, cameos, and archaeological motifs spread through ceramics, silver, textiles, and type.']},
  {id:'romanticism',name:'Romanticism',date:'c. 1780–1850',summary:'Emotion, imagination, history, and untamed nature rebelled against industrial discipline and pure reason.',art:'Storm, ruin, dramatic color, distant horizons, and vulnerable figures turn landscape into psychological experience.',impacts:['Political|Revolution, nationalism, and struggles for independence made freedom, heroism, and popular identity urgent subjects.','Social|Artists elevated individual feeling, folklore, and the outsider while questioning the costs of modern rational society.','Economic|Industrialization transformed landscapes and labor, fueling both fascination with progress and longing for escape.','Military|Napoleonic war, occupation, massacre, and revolt entered art as trauma rather than only triumph.'],works:['The Third of May 1808|Francisco Goya · 1814|Anonymous victims and harsh light strip war of heroic distance.','Wanderer above the Sea of Fog|Caspar David Friedrich · c. 1818|A solitary viewer confronts nature’s unknowable scale.','The Slave Ship|J. M. W. Turner · 1840|Color and storm indict violence within global commerce.'],design:['Architecture|Gothic Revival, ruins, cottages, and picturesque planning valued atmosphere, history, and irregularity.','Furniture|Dark carved wood, pointed arches, natural motifs, and handcrafted references challenged classical restraint.','Design|Folklore, medievalism, exoticism, and botanical pattern shaped books, textiles, interiors, and gardens.']},
  {id:'realism',name:'Realism',date:'c. 1840–1880',summary:'Artists turned from gods and heroes to labor, inequality, modern streets, and the observable conditions of their own time.',art:'Earth color, unidealized bodies, ordinary scale, and direct observation insist that contemporary life deserves serious attention.',impacts:['Political|The revolutions of 1848 and expanding socialist thought pushed class conflict and ordinary citizenship into view.','Social|Urbanization exposed poverty, crowded housing, gendered labor, and rural displacement to new scrutiny.','Economic|Factories, railways, wage labor, and commodity markets reordered daily life and who could buy or exhibit art.','Military|Conscription, civil conflict, and new reportage encouraged less idealized images of soldiers and war’s aftermath.'],works:['The Stone Breakers|Gustave Courbet · 1849|Exhausting labor occupies the scale once reserved for history painting.','The Gleaners|Jean-François Millet · 1857|Rural poverty appears monumental and socially unsettling.','The Horse Fair|Rosa Bonheur · 1852–55|Close observation and physical energy transform an urban market into spectacle.'],design:['Architecture|Factories, worker housing, rail sheds, and iron bridges prioritized function, span, repetition, and infrastructure.','Furniture|Bentwood, cast iron, sewing machines, and factory ceramics brought designed goods to mass markets.','Design|Mechanization separated designer from maker and provoked later reform movements focused on honest craft.']},
  {id:'impressionism',name:'Impressionism',date:'c. 1860–1886',summary:'Modern mobility, leisure, photography, and new color science taught artists to paint perception as a fleeting event.',art:'Broken strokes, high-key color, cropped views, reflections, and changing weather capture the instability of vision.',impacts:['Political|A rebuilt Paris, the Franco-Prussian War, and the Commune changed public space and the artists who pictured it.','Social|Boulevards, cafés, theaters, parks, and suburbs produced new forms of leisure, looking, and gendered public life.','Economic|Department stores, dealers, collectors, and independent exhibitions weakened the official Salon’s monopoly.','Military|War displaced artists and opened contact with London; afterward, reconstruction and national identity framed modern life.'],works:['Impression, Sunrise|Claude Monet · 1872|Loose marks and colored atmosphere privilege sensation over finish.','The Cradle|Berthe Morisot · 1872|Modern domestic life is rendered with intimacy and formal daring.','The Ballet Class|Edgar Degas · 1874|Cropping and unusual viewpoints reveal labor behind urban entertainment.'],design:['Architecture|Iron-and-glass pavilions, boulevards, apartment blocks, cafés, and stations made modern life transparent and mobile.','Furniture|Bentwood café chairs and lighter interiors suited public leisure and new middle-class apartments.','Design|Japanese prints transformed asymmetry, cropping, flat pattern, posters, ceramics, and fashionable interiors.']},
  {id:'post-impressionism',name:'Post-Impressionism',date:'c. 1886–1905',summary:'Artists kept Impressionism’s color but demanded more structure, symbolism, system, and emotional force.',art:'Geometric planes, optical dots, rhythmic marks, flattened pattern, and expressive color move beyond immediate appearance.',impacts:['Political|Colonial expansion, anarchism, and industrial unrest shaped artists’ searches for alternatives to bourgeois Europe.','Social|Urban alienation and new psychological ideas encouraged inward, symbolic, and deliberately personal visual worlds.','Economic|The dealer-critic system and independent groups let artists develop recognizable individual styles for a growing market.','Military|Imperial competition and colonial occupation enabled cultural contact while distorting non-European cultures through unequal power.'],works:['A Sunday on La Grande Jatte|Georges Seurat · 1884–86|Optical color and frozen leisure make modern society feel both ordered and strange.','The Starry Night|Vincent van Gogh · 1889|Directional paint turns landscape into emotional and spiritual energy.','Mont Sainte-Victoire|Paul Cézanne · c. 1902–06|Color planes rebuild nature as a stable visual structure.'],design:['Architecture|Simplified massing and expressive surfaces anticipated Art Nouveau and early modern approaches.','Furniture|Sinuous lines, handcrafted unity, painted ceramics, and bold textiles sought an artful alternative to mass production.','Design|Flat color, contour, poster art, and total-interior thinking joined fine and applied arts.']},
  {id:'modernism',name:'Modernism',date:'c. 1905–1970',summary:'Artists dismantled inherited representation to answer machines, mass media, world war, psychology, and radical politics.',art:'Fragmentation, abstraction, collage, dream imagery, industrial materials, and bold geometry make form itself the subject.',impacts:['Political|Revolution, fascism, communism, democracy, and decolonization turned visual culture into a contested ideological field.','Social|Mass urban society, psychoanalysis, feminism, migration, and new media challenged stable identity and tradition.','Economic|Industrial production and consumer culture inspired both functional design for all and critique through appropriation and Pop.','Military|Two world wars, genocide, exile, atomic weapons, and the Cold War profoundly changed artists, institutions, and global centers.'],works:['Les Demoiselles d’Avignon|Pablo Picasso · 1907|Fractured bodies and space break decisively with Renaissance illusion.','Composition VIII|Wassily Kandinsky · 1923|Geometry, rhythm, and color operate independently of observed subjects.','The Two Fridas|Frida Kahlo · 1939|A doubled self-portrait joins personal identity, politics, and symbolic anatomy.'],design:['Architecture|Steel, glass, concrete, open plans, and “form follows function” rejected applied historical ornament.','Furniture|Tubular steel, plywood, standardization, and ergonomic experiments aligned objects with machine production.','Graphic design|Grids, sans-serif type, photomontage, and asymmetric layout made information direct and reproducible.']},
  {id:'contemporary',name:'Contemporary Art',date:'c. 1970–Now',summary:'With no single center or medium, artists use objects, bodies, data, communities, and spaces to question the present.',art:'Installation, participation, image circulation, code, reused material, performance, and painting coexist in a plural field.',impacts:['Political|Civil-rights, feminist, queer, Indigenous, and decolonial movements changed whose histories enter museums and public space.','Social|Identity, migration, ecology, surveillance, and networked life make audiences participants rather than only viewers.','Economic|Global fairs, mega-galleries, cultural tourism, and digital markets coexist with institutional critique and community practice.','Military|Cold War legacies, terrorism, occupation, drones, displacement, and protest shape work about borders, memory, and power.'],works:['Untitled|Jean-Michel Basquiat · 1982|Layered figures, words, and symbols confront race, history, value, and urban culture.','Infinity Mirror Rooms|Yayoi Kusama · 1965–present|Reflection, repetition, and the viewer create an immersive perceptual environment.','A Subtlety|Kara Walker · 2014|Monumental scale links sugar, labor, race, gender, and industrial space.'],design:['Architecture|Adaptive reuse, parametric form, community co-design, and low-carbon material systems broaden architectural priorities.','Furniture|Recycled biomaterials, digital fabrication, modularity, and collectible experimentation blur craft and technology.','Design|Interfaces, service systems, accessibility, circularity, and participatory methods expand design beyond physical objects.']}
];

const workImages=periodWorkSlugs;

const params=new URLSearchParams(location.search);let index=periods.findIndex(p=>p.id===params.get('era'));if(index<0)index=0;const p=periods[index];
const story=periodStories[p.id];
const experience=experienceData[p.id];
document.body.dataset.era=p.id;document.title=`${p.name} — Art Compass`;document.documentElement.style.setProperty('--accent', ['#b7442a','#d7a63f','#e7c654','#d9d0b8','#8b151b','#c7b88e','#566d61','#9c8661','#a7c9df','#e9bd24','#e32822','#dcff44'][index]);
const $=id=>document.getElementById(id);$('chapter').textContent=`Chapter ${String(index+1).padStart(2,'0')} · ${p.date}`;$('title').textContent=p.name;$('summary').textContent=p.summary;$('back-link').href=`./#${p.id}`;
$('era-answer').textContent=experience.answer;$('emotion-arc').innerHTML=`<span>${experience.emotion[0]}</span><i aria-hidden="true"></i><span>${experience.emotion[1]}</span>`;
$('story-thesis').textContent=story.thesis;$('story-world').textContent=story.world;$('story-catalyst').textContent=story.catalyst;$('story-seeing').textContent=story.seeing;$('story-legacy').textContent=story.legacy;$('story-transition').textContent=story.transition;
$('glossary-jump').innerHTML=`Vocabulary for this chapter: ${eraGlossary[p.id].map(term=>`<a href="glossary.html#term-${term.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}">${term}</a>`).join(' · ')}`;
$('time-now').textContent=`${p.name} · ${p.date}`;$('time-stops').innerHTML=periods.map((period,i)=>`<a href="explore.html?era=${period.id}" ${i===index?'aria-current="page"':''}><i></i><span>${period.name}</span><small>${period.date}</small></a>`).join('');
$('architecture-image').src=`assets/explore/${p.id}-architecture.jpg`;$('architecture-image').alt=`Original architectural study inspired by ${p.name}`;$('architecture-caption').textContent=p.design[0].split('|')[1];
$('design-image').src=`assets/explore/${p.id}-design.jpg`;$('design-image').alt=`Original furniture and decorative design study inspired by ${p.name}`;$('design-caption').textContent=p.design[1].split('|')[1];
$('impacts').innerHTML=p.impacts.map((x,i)=>{const [h,t]=x.split('|');return `<article class="impact"><span class="num">0${i+1}</span><h3>${h}</h3><p>${t}</p></article>`}).join('');
$('origins').insertAdjacentHTML('afterend',`<section class="turning-point"><p class="overline">The visual turning point</p><h2>Watch a worldview <em>change.</em></h2><div class="rupture-stage"><article><span>${experience.rupture[0]}</span><p>${experience.rupture[1]}</p></article><button type="button" aria-pressed="false">Reveal the shift →</button><article><span>${experience.rupture[2]}</span><p>${experience.rupture[3]}</p></article></div><div class="visual-dna"><p>Visual DNA</p>${experience.dna.map((item,i)=>`<div><i style="--dna:${i}"></i><span>${item}</span></div>`).join('')}</div></section>`);const rupture=document.querySelector('.turning-point');rupture.querySelector('button').addEventListener('click',event=>{const revealed=rupture.classList.toggle('revealed');event.currentTarget.setAttribute('aria-pressed',String(revealed));event.currentTarget.textContent=revealed?'Return to before ←':'Reveal the shift →'});
$('exchange-list').innerHTML=periodContext[p.id].map(([lens,cause,effect],i)=>`<article class="exchange-row"><div class="exchange-heading"><span>${String(i+1).padStart(2,'0')}</span><h3>${lens}</h3></div><div><b>What shaped the art</b><p>${cause}</p></div><i aria-hidden="true">→</i><div><b>What the art changed</b><p>${effect}</p></div></article>`).join('');
const resources=periodResources[p.id];
const learning=learningData[p.id];$('reflection-prompt').textContent=learning.prompt;
$('parallel-worlds').innerHTML=parallelWorlds[p.id].map(([title,text])=>`<article><h3>${title}</h3><p>${text}</p></article>`).join('');
$('idea-study').innerHTML=`<div><p class="overline">Defining shift in thought</p><h3>${periodIdeas[p.id][0]}</h3><p>${periodIdeas[p.id][1]}</p><aside class="thought-context"><b>${thoughtContext[p.id][0]}</b><p>${thoughtContext[p.id][1]}</p></aside></div>${p.id==='ancient'?'<figure class="forms-study" aria-label="An imperfect physical circle compared with the concept of a perfect circle"><div><i class="drawn-circle"></i><b>The drawn circle</b><span>Physical · changing · imperfect</span></div><em>→</em><div><i class="ideal-circle"></i><b>The perfect circle</b><span>Intelligible · exact · ideal</span></div><figcaption>The drawing is only an example. The perfect mathematical circle is grasped through reason.</figcaption></figure>':''}`;
$('books-list').innerHTML=resources.books.map(([title,meta,why],i)=>`<article class="book-row ${i===0?'featured-voice':''}"><span>${String(i+1).padStart(2,'0')}</span><h3>${title}<small>${meta}</small></h3><p>${why}</p></article>`).join('');

const projectPoint=([longitude,latitude])=>[(longitude+180)/360*1000,(90-latitude)/180*500];
const ringPath=ring=>ring.map((point,i)=>{const[x,y]=projectPoint(point);return`${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`}).join('')+'Z';
const geometryPath=geometry=>geometry.type==='Polygon'?geometry.coordinates.map(ringPath).join(''):geometry.coordinates.map(polygon=>polygon.map(ringPath).join('')).join('');
Promise.resolve(window.worldMapData).then(world=>{
  const group=$('map-countries'),core=new Set(resources.core),influence=resources.influence==='all'?null:new Set(resources.influence);
  world.features.forEach(feature=>{const code=feature.properties.ADM0_A3,path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',geometryPath(feature.geometry));path.setAttribute('class',core.has(code)?'map-core':resources.influence==='all'||influence.has(code)?'map-influence':'map-land');path.appendChild(document.createElementNS('http://www.w3.org/2000/svg','title')).textContent=feature.properties.ADMIN;group.appendChild(path)});
  const namesFor=set=>world.features.filter(feature=>set.has(feature.properties.ADM0_A3)).map(feature=>feature.properties.ADMIN).sort().join(', ');
  $('map-regions').innerHTML=`<p><b>Representative centers:</b> ${namesFor(core)}</p><p><b>Wider influence and exchange:</b> ${resources.influence==='all'?'Globally networked; emphasis varies by institution, market, and local history.':namesFor(influence)}</p>`;
}).catch(()=>{$('map-countries').innerHTML='<text x="500" y="250" text-anchor="middle">Map unavailable</text>'});
$('map-title').textContent=`World context for ${p.name}`;$('map-description').textContent=`Representative centers and wider influence associated with ${p.name}. Modern borders are used only for orientation.`;$('map-note').textContent=resources.note;
$('map-note').insertAdjacentHTML('afterend',`<div class="exchange-route"><i aria-hidden="true"><span></span></i><p><b>${experience.route[0]}</b>${experience.route[1]}</p></div>`);
$('works').innerHTML=p.works.map((x,i)=>{const [h,m,t]=x.split('|'),slug=workImages[p.id][i],record=workRecords[slug],source=record.source,media=window.artworkMedia?.[slug],imagePath=media?.path||`assets/works/${slug}.jpg`,imageAlt=media?`Reproduction of ${h}`:`AI-generated visual study showing the contribution of ${h}`,badge=media?'Artwork reproduction':'Interpretive study';const credit=media?`<span>${media.license}; image credit: ${media.artist}</span><span>Rights record retained in the local attribution data.</span>`:'<span>AI-generated—not the original artwork</span>';const metadata=[record.medium,record.dimensions,record.location].filter(Boolean).map(value=>`<li>${value}</li>`).join('');return `<article class="work-row"><span>0${i+1}</span><figure class="work-study"><button class="image-open" type="button" data-image="${imagePath}" data-alt="${imageAlt}" data-caption="${h} · ${m}" aria-label="Open a larger view of ${h}"><img class="work-image" src="${imagePath}" alt="${imageAlt}" loading="lazy"><i>Open full image</i></button><figcaption><b>${badge}</b>${credit}</figcaption></figure><div class="work-title"><h3>${h}<br><small>${m}</small></h3><ul class="object-meta">${metadata}</ul></div><div class="work-reading"><b class="work-role">${story.roles[i]}</b><h4>What changed here</h4><p>${t}</p><details class="looking-reveal"><summary>Look first, then reveal two clues</summary><ul class="notice-list">${record.notice.map(item=>`<li>${item}</li>`).join('')}</ul></details><span class="collection-link">Source record: ${source[0]} · ${source[1]}</span></div></article>`}).join('');
const eraWorkSources=workImages[p.id].map(slug=>workRecords[slug].source);$('era-sources').innerHTML=eraWorkSources.map(([title,institution])=>`<li><div><b>${title}</b><span>${institution}</span></div></li>`).join('');
$('works').insertAdjacentHTML('afterend',`<aside class="scale-study"><div class="scale-figure" aria-hidden="true"><i></i><span></span></div><div><p class="overline">Feel the physical scale</p><h3>${experience.scale[0]}</h3><b>${experience.scale[1]}</b><p>${experience.scale[2]}</p></div></aside>`);
$('design-intro').textContent=`The period’s ideas did not stop at art. They changed the spaces people built, the objects they touched, and the visual systems that organized daily life.`;
$('design-notes').innerHTML=p.design.map(x=>{const[h,t]=x.split('|');return `<article><h3>${h}</h3><p>${t}</p></article>`}).join('');
const previous=periods[(index-1+periods.length)%periods.length],next=periods[(index+1)%periods.length];$('previous').href=`explore.html?era=${previous.id}`;$('previous').textContent=`← ${previous.name}`;$('next').href=`explore.html?era=${next.id}`;$('next').textContent=`${next.name} →`;
const compareFigure=(period,slug)=>{const item=workRecords[slug],media=window.artworkMedia?.[slug],src=media?.path||`assets/works/${slug}.jpg`;return `<figure><img src="${src}" alt="${media?'Reproduction':'Interpretive study'} for ${item.source[0]}" loading="lazy"><figcaption><b>${period.name}</b><span>${item.source[0]}</span></figcaption></figure>`};const priorSlug=index?workImages[previous.id][2]:workImages[p.id][0],currentSlug=index?workImages[p.id][0]:workImages[next.id][0];$('era-compare').innerHTML=`<p class="overline">Visual comparison</p><h3>${index?`${previous.name} → ${p.name}`:`${p.name} → ${next.name}`}</h3><div class="compare-images">${compareFigure(index?previous:p,priorSlug)}<i aria-hidden="true">→</i>${compareFigure(index?p:next,currentSlug)}</div><div class="compare-questions"><p><b>Form</b>What changed in space, body, surface, or composition?</p><p><b>Worldview</b>What does each work assume about truth, authority, or human experience?</p><p><b>Institution</b>Who enabled each work to exist, and who was expected to see it?</p></div>${index?`<a href="explore.html?era=${previous.id}">Return to ${previous.name} for a closer comparison</a>`:''}`;

const viewer=$('image-viewer'),viewerImage=$('viewer-image'),viewerCaption=$('viewer-caption');$('works').addEventListener('click',event=>{const button=event.target.closest('.image-open');if(!button)return;viewerImage.src=button.dataset.image;viewerImage.alt=button.dataset.alt;viewerCaption.textContent=button.dataset.caption;viewer.showModal()});$('viewer-close').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',event=>{if(event.target===viewer)viewer.close()});
const study=studyData[p.id],quiz=study.quiz;$('takeaways').innerHTML=study.takeaways.map(item=>`<li>${item}</li>`).join('');$('quiz-question').textContent=quiz[0];$('quiz-options').innerHTML=quiz[1].map((answer,i)=>`<label><input type="radio" name="answer" value="${i}"> ${answer}</label>`).join('');$('knowledge-check').addEventListener('submit',event=>{event.preventDefault();const answer=new FormData(event.currentTarget).get('answer');$('quiz-result').textContent=answer===null?'Choose an answer first.':Number(answer)===quiz[2]?'Correct. You have identified the chapter’s central distinction.':`Not quite. Return to the chapter synthesis and try again.`});const progressKey='art-compass-progress';const getProgress=()=>{try{return JSON.parse(localStorage.getItem(progressKey)||'[]')}catch{return[]}},showProgress=()=>{const done=getProgress();$('progress-status').textContent=`${done.length} of ${periods.length} chapters marked complete. Progress stays only on this device.`;$('mark-complete').textContent=done.includes(p.id)?'Chapter complete ✓':'Mark chapter complete'};$('mark-complete').addEventListener('click',()=>{const done=new Set(getProgress());done.add(p.id);try{localStorage.setItem(progressKey,JSON.stringify([...done]));showProgress()}catch{$('progress-status').textContent='Progress storage is unavailable in this browser mode.'}});showProgress();

const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const motionButton=$('motion-toggle');if(reducedMotion.matches){motionButton.textContent='Motion reduced';motionButton.disabled=true;motionButton.setAttribute('aria-pressed','true')}
motionButton.addEventListener('click',()=>{const paused=document.body.classList.toggle('motion-paused');motionButton.setAttribute('aria-pressed',String(paused));motionButton.textContent=paused?'Resume motion':'Pause motion';if(paused)document.querySelectorAll('main>section,.hero-image').forEach(section=>section.classList.add('in-view'))});
if(!reducedMotion.matches){
  document.body.classList.add('motion-ready');
  const hero=document.querySelector('.explore-hero');let frame;
  const setView=(x,y)=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{hero.style.setProperty('--look-x',`${x}deg`);hero.style.setProperty('--look-y',`${y}deg`)})};
  hero.addEventListener('pointermove',event=>{const box=hero.getBoundingClientRect();setView(((event.clientY-box.top)/box.height-.5)*-8,((event.clientX-box.left)/box.width-.5)*10)});
  hero.addEventListener('pointerleave',()=>setView(0,0));
  addEventListener('scroll',()=>{const depth=Math.min(1,scrollY/Math.max(hero.offsetHeight,1));hero.style.setProperty('--scroll-z',`${Math.round(depth*-90)}px`)},{passive:true});
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -8%'});
  document.querySelectorAll('main>section,.hero-image').forEach(section=>observer.observe(section));
}
const acts=[...document.querySelectorAll('.story-act')];const actObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const act=acts.indexOf(entry.target)+1;$('time-now').textContent=`${p.name} · Act ${act} of ${acts.length}`}}),{rootMargin:'-35% 0px -55%',threshold:0});acts.forEach(act=>actObserver.observe(act));
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
document.querySelectorAll('.period-nav a,.time-rail a').forEach(link=>link.addEventListener('click',event=>{if(reducedMotion.matches)return;event.preventDefault();document.body.classList.add('era-leaving');setTimeout(()=>location.href=link.href,260)}));
