window.learningData={
prehistoric:{prompt:'What changes when an image is understood as memory or ritual rather than decoration?',sources:[['Lascaux Cave','French Ministry of Culture','https://archeologie.culture.gouv.fr/lascaux/en'],['Stonehenge history','English Heritage','https://www.english-heritage.org.uk/visit/places/stonehenge/history-and-stories/'],['Prehistoric art','The Metropolitan Museum of Art','https://www.metmuseum.org/toah/'] ]},
ancient:{prompt:'Where does idealization end and political persuasion begin?',sources:[['Greek and Roman art','The Metropolitan Museum of Art','https://www.metmuseum.org/about-the-met/collection-areas/greek-and-roman-art'],['The Parthenon Gallery','Acropolis Museum','https://www.theacropolismuseum.gr/en/parthenon-gallery'],['Ancient Greece','British Museum','https://www.britishmuseum.org/collection/galleries/greece-parthenon']]},
medieval:{prompt:'How can a material object direct attention toward something believed to be immaterial?',sources:[['Medieval art and The Cloisters','The Metropolitan Museum of Art','https://www.metmuseum.org/about-the-met/collection-areas/medieval-art-and-the-cloisters'],['Book of Kells','Trinity College Dublin','https://www.visittrinity.ie/book-of-kells-experience/'],['Chartres Cathedral','UNESCO World Heritage Centre','https://whc.unesco.org/en/list/81/']]},
renaissance:{prompt:'How does perspective place the viewer—and the individual—inside a new model of reality?',sources:[['Birth of Venus','Uffizi Galleries','https://www.uffizi.it/en/artworks/birth-of-venus'],['Mona Lisa','Musée du Louvre','https://www.louvre.fr/en/explore/the-palace/from-the-mona-lisa-to-the-wedding-feast-at-cana'],['Michelangelo’s David','Galleria dell’Accademia di Firenze','https://www.galleriaaccademiafirenze.it/en/artworks/david-michelangelo/']]},
baroque:{prompt:'When does emotional immersion deepen understanding, and when does it become manipulation?',sources:[['David by Bernini','Galleria Borghese','https://galleriaborghese.beniculturali.it/en/opera/david/'],['Judith Slaying Holofernes','Uffizi Galleries','https://www.uffizi.it/en/artworks/judith-beheading-holofernes'],['European paintings','The Metropolitan Museum of Art','https://www.metmuseum.org/about-the-met/collection-areas/european-paintings']]},
neoclassicism:{prompt:'Why could the same classical language represent both republican liberty and imperial authority?',sources:[['Oath of the Horatii','Musée du Louvre','https://collections.louvre.fr/en/ark:/53355/cl010062239'],['European art','National Gallery of Art','https://www.nga.gov/collection/european-art.html'],['Enlightenment','British Museum','https://www.britishmuseum.org/collection/galleries/enlightenment']]},
romanticism:{prompt:'What kinds of truth become visible when emotion and imagination are treated as knowledge?',sources:[['The Third of May 1808','Museo del Prado','https://www.museodelprado.es/en/the-collection/art-work/the-3rd-of-may-1808-in-madrid-or-the-executions/5e177409-2993-4240-97fb-847a02c6496c'],['The Slave Ship','Museum of Fine Arts Boston','https://collections.mfa.org/objects/31102'],['Romanticism','The Metropolitan Museum of Art','https://www.metmuseum.org/toah/']]},
realism:{prompt:'Can representing ordinary life objectively ever be politically neutral?',sources:[['The Gleaners','Musée d’Orsay','https://www.musee-orsay.fr/en/artworks/des-glaneuses-342'],['The Horse Fair','The Metropolitan Museum of Art','https://www.metmuseum.org/art/collection/search/435702'],['European paintings','The Metropolitan Museum of Art','https://www.metmuseum.org/about-the-met/collection-areas/european-paintings']]},
impressionism:{prompt:'If perception changes from moment to moment, what kind of truth can a painting preserve?',sources:[['The Cradle','Musée d’Orsay','https://www.musee-orsay.fr/en/artworks/le-berceau-1132'],['Impressionism','National Gallery of Art','https://www.nga.gov/features/slideshows/impressionism.html'],['European paintings','The Metropolitan Museum of Art','https://www.metmuseum.org/about-the-met/collection-areas/european-paintings']]},
'post-impressionism':{prompt:'Which is more truthful: observed appearance, emotional experience, or underlying structure?',sources:[['A Sunday on La Grande Jatte','Art Institute of Chicago','https://www.artic.edu/artworks/27992/a-sunday-on-la-grande-jatte-1884'],['The Starry Night','Museum of Modern Art','https://www.moma.org/collection/works/79802'],['Cézanne','Philadelphia Museum of Art','https://philamuseum.org/collection/curated/paul-cezanne']]},
modernism:{prompt:'What is gained—and who is excluded—when artists declare a complete break with tradition?',sources:[['Les Demoiselles d’Avignon','Museum of Modern Art','https://www.moma.org/collection/works/79766'],['Composition 8','Solomon R. Guggenheim Museum','https://www.guggenheim.org/artwork/1924'],['Modern and contemporary art','The Metropolitan Museum of Art','https://www.metmuseum.org/about-the-met/collection-areas/modern-and-contemporary-art']]},
contemporary:{prompt:'Who determines an artwork’s meaning: the artist, institution, market, community, or participant?',sources:[['Jean-Michel Basquiat','Whitney Museum of American Art','https://whitney.org/artists/387'],['Yayoi Kusama','Tate','https://www.tate.org.uk/art/artists/yayoi-kusama-8094'],['A Subtlety','Creative Time','https://creativetime.org/projects/karawalker/']]}
};

window.glossary={
  'Abstraction':'Art that emphasizes form, color, line, material, or concept rather than recognizable representation.',
  'Chiaroscuro':'Strong modeling through contrasts of light and dark.',
  'Contrapposto':'A standing pose in which weight rests primarily on one leg, creating an asymmetrical body.',
  'Humanism':'Study centered on human language, agency, history, and classical learning.',
  'Idealization':'Changing observed features to embody a preferred standard or concept.',
  'Iconography':'The subjects, symbols, and conventional meanings within images.',
  'Linear perspective':'A geometric system for representing depth through converging parallel lines.',
  'Naturalism':'Representation that closely observes the appearance and behavior of the visible world.',
  'Patronage':'Financial or institutional support that enables art to be produced.',
  'Sfumato':'Soft transitions between tones that create atmospheric depth and uncertain edges.',
  'The sublime':'An experience of awe, vastness, danger, or power that exceeds ordinary comprehension.',
  'Tenebrism':'Dramatic illumination in which figures emerge from dominant darkness.'
};

window.parallelWorlds={
prehistoric:[['Across inhabited regions','Rock art, body ornament, carved objects, weaving, pottery, and monument building developed through many independent local traditions.'],['Different chronologies','Communities adopted agriculture, settlement, and metallurgy at different times; “prehistoric” is a condition of surviving evidence, not a universal stage.']],
ancient:[['Asia and Africa','Chinese dynasties, South Asian empires, Persian states, and African kingdoms developed distinct courtly, sacred, funerary, and philosophical traditions.'],['The Americas','Olmec, Maya, Andean, and other societies built cities, monuments, calendars, and visual systems independently of Mediterranean antiquity.']],
medieval:[['Islamic worlds','Caliphates and regional courts connected scholarship, architecture, calligraphy, trade, and scientific exchange from Iberia to Central and South Asia.'],['Africa, Asia, and the Americas','Mali, Great Zimbabwe, Song China, Heian Japan, Angkor, and major American societies followed histories not contained by Europe’s “Middle Ages.”']],
renaissance:[['Powerful contemporaries','The Ottoman, Safavid, Mughal, Ming, Benin, Aztec, and Inca states sustained sophisticated visual and intellectual cultures.'],['Unequal encounter','European expansion connected these worlds through trade, diplomacy, conversion, violence, extraction, and cultural adaptation.']],
baroque:[['Court cultures beyond Europe','Mughal, Safavid, Ottoman, Qing, and Edo-period patrons developed distinctive painting, architecture, gardens, textiles, and ceremonial spaces.'],['Colonial transformation','Artists in Latin America, Africa, and Asia remade European forms through local materials, knowledge, labor, and belief under unequal imperial rule.']],
neoclassicism:[['More than one modernity','Qing China, Ottoman reform, African states, Indigenous nations, and South Asian powers negotiated commerce and political change on their own terms.'],['The Atlantic contradiction','Claims of liberty and universal rights coexisted with slavery, colonial expansion, Indigenous dispossession, and restricted citizenship.']],
romanticism:[['Empire shapes imagination','European fascination with distant landscapes and cultures was enabled by colonial power and often converted difference into fantasy.'],['National and anticolonial cultures','Writers and artists across Europe and the Americas used history, folklore, and emotion to construct national or liberatory identities.']],
realism:[['Global modernizations','Meiji Japan, late Qing China, the Ottoman world, colonial cities, and independent American states developed distinct responses to industry and social change.'],['Camera and empire','Photography and illustrated print documented modern life while also classifying colonized peoples through unequal systems of observation.']],
impressionism:[['Japan as active source','Japanese prints and design profoundly affected European composition, while Meiji artists selectively negotiated Western materials and institutions.'],['Modern life was global','Ports, colonial trade, migration, and commodity networks underwrote the leisure and urban surfaces pictured in European modern art.']],
'post-impressionism':[['Colonial access','Artists’ searches for alternatives to Europe relied on objects, travel, and fantasies produced through empire. Innovation must be studied beside appropriation.'],['Multiple experiments','Symbolist, reform, nationalist, and hybrid visual movements developed across Europe, the Americas, Asia, and colonial cultural centers.']],
modernism:[['Modernisms, plural','Artists in Mexico, Brazil, Japan, India, Africa, the Caribbean, and elsewhere transformed—not merely received—international modernist languages.'],['Migration and decolonization','Exile, diaspora, anticolonial struggle, and new nations changed where modern art was made and who could define the modern.']],
contemporary:[['No single center','Artists work through local histories within global networks of migration, biennials, education, media, markets, and activism.'],['Unequal visibility','Global participation does not erase disparities in wealth, mobility, museum authority, internet access, cultural extraction, or whose work enters the canon.']]
};
