window.studyData={
prehistoric:{takeaways:['Symbolic making predates writing.','Material, place, memory, and ritual cannot be separated.','“Prehistoric” names surviving evidence, not one global culture.'],quiz:['Why are modern country borders only orientation on this chapter’s map?',['The borders did not exist in these periods','Every community shared one government','Rock art was limited to Europe'],0]},
ancient:{takeaways:['Cities and states made art a durable language of authority.','Ideal form expressed how order ought to appear.','Antiquity includes independent traditions far beyond Greece and Rome.'],quiz:['What does idealization do in many ancient state images?',['Records every accidental detail','Makes political and sacred order appear stable','Eliminates social hierarchy'],1]},
medieval:{takeaways:['Images directed material attention toward spiritual meaning.','Manuscript, building, object, and ritual formed integrated environments.','Europe’s Middle Ages overlapped with distinct flourishing societies elsewhere.'],quiz:['Why is gold often spatially different from naturalistic background?',['It signals ordinary daylight','It denies ordinary atmosphere and suggests sacred presence','It was always the cheapest pigment'],1]},
renaissance:{takeaways:['Perspective organized space around a human observer.','Humanism joined classical learning to agency and historical judgment.','Trade, empire, and print complicate the idea of an isolated European rebirth.'],quiz:['What did linear perspective newly coordinate?',['A coherent measured space and viewing position','Only the price of paintings','The chemical composition of marble'],0]},
baroque:{takeaways:['Art became an immersive instrument of persuasion.','Movement and light made viewers feel present at an event.','Colonial wealth and local transformation shaped Baroque forms globally.'],quiz:['Why do Baroque compositions often cross the viewer’s boundary?',['To create emotional and bodily participation','To restore medieval flatness','To eliminate narrative'],0]},
neoclassicism:{takeaways:['Antiquity served both revolutionary and imperial politics.','Clarity and contour turned scenes into moral arguments.','Universal rights were proclaimed within deeply exclusionary systems.'],quiz:['What central contradiction shaped Neoclassical politics?',['Liberty coexisted with slavery and restricted citizenship','Archaeology rejected antiquity','Republics refused classical imagery'],0]},
romanticism:{takeaways:['Emotion and imagination were treated as knowledge.','The sublime joined awe, beauty, danger, and power.','Empire enabled many supposedly distant or exotic visions.'],quiz:['What does the Romantic sublime describe?',['Perfect administrative order','Experience exceeding ordinary comprehension','Mechanical reproduction'],1]},
realism:{takeaways:['Ordinary labor acquired the seriousness of history painting.','Observation was never politically neutral.','Industry and mass media altered both subjects and audiences.'],quiz:['Why could depicting workers at monumental scale be political?',['Scale had traditionally signaled prestigious subjects','Workers commissioned every academy','Large canvases were legally prohibited'],0]},
impressionism:{takeaways:['Perception changes with time, light, motion, and attention.','Independent exhibitions weakened official control.','Modern leisure depended on global commodities and unequal networks.'],quiz:['What do broken brushstrokes ask the viewer to do?',['Assemble the sensation optically','Ignore color','Read a fixed symbolic code'],0]},
'post-impressionism':{takeaways:['No single style followed Impressionism.','Structure, emotion, symbol, and optical system offered competing truths.','Innovation must be studied alongside colonial access and appropriation.'],quiz:['What united Post-Impressionist experiments?',['A return to one academic rule','Dissatisfaction with fleeting appearance alone','Rejection of expressive color'],1]},
modernism:{takeaways:['Modernisms developed through many centers, migrations, and conflicts.','Form itself became a way to investigate fractured experience.','Radical freedom coexisted with exclusions and appropriation.'],quiz:['Why is “modernisms” often more accurate than “Modernism”?',['Artists worldwide transformed modernity through distinct histories','Every artist used identical geometry','The movement had no institutions'],0]},
contemporary:{takeaways:['No medium or geographic center defines the field.','Meaning can reside in context, participation, and systems.','Global visibility remains structured by unequal power and resources.'],quiz:['Who may participate in producing contemporary meaning?',['Only the artist','Artist, audience, institution, community, and context','Only the market'],1]}
};
window.thoughtContext={
prehistoric:['Many knowledge systems','No single author defines symbolic thought; archaeological evidence must be interpreted alongside living Indigenous knowledge without treating present communities as fossils of the past.'],
ancient:['Plato, Aristotle, Confucian, Buddhist, and other traditions','Plato’s Forms are one influential answer, not the ancient world’s consensus. Empirical, relational, ethical, and material accounts of reality developed alongside it.'],
medieval:['Christian, Jewish, Islamic, Byzantine, and scholastic thinkers','Cosmic order was debated across languages and faiths. Reason, revelation, commentary, and mysticism offered different paths to knowledge.'],
renaissance:['Petrarch, Alberti, Erasmus, and humanist networks','Human dignity and classical recovery expanded inquiry while education, citizenship, gender, and colonial power limited who could claim the universal human.'],
baroque:['Descartes, Pascal, Bacon, and scientific communities','Rational certainty, experiment, faith, and skepticism competed. The period’s art often makes that instability physically persuasive.'],
neoclassicism:['Rousseau, Wollstonecraft, Diderot, and revolutionary publics','Universal reason enabled radical critique, yet slavery, empire, property, race, and gender exposed the boundaries of proclaimed equality.'],
romanticism:['Kant, Burke, Wordsworth, Goethe, and anticolonial national cultures','Imagination could resist mechanical reason, but concepts of genius, nature, and the exotic also carried nationalist and imperial assumptions.'],
realism:['Marx, Engels, positivists, novelists, and social reformers','Material conditions became explanatory, but artists disputed whether observation could ever be objective or separate from class position.'],
impressionism:['Baudelaire, optical science, photography, and modern spectators','Immediate perception appeared personal while being shaped by physiology, technology, urban planning, gender, class, and learned attention.'],
'post-impressionism':['Nietzsche, Freud, symbolism, optics, and artists’ individual systems','Inner truth might mean emotion, unconscious desire, spiritual symbol, or geometric order—solutions that could not be reduced to one theory.'],
modernism:['Freud, Einstein, Marxism, formalism, feminism, and decolonial thought','The break with tradition promised universality while often centering European institutions and extracting forms from cultures denied equal authority.'],
contemporary:['Situated knowledge, intersectionality, postcolonial and Indigenous thought','Standpoint and context challenge universal authority, while debate continues over relativism, shared evidence, cultural ownership, and institutional power.']
};
